plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.version
group = project.group

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

def modProps = [
        "group"                 : project.group,
        "id"                      : project.id,
        "name"                    : project.name,
        "version"                 : project.version,
        "description"                 : project.description,
        "authors"                     : project.authors,
        "homepage"                    : project.homepage,
        "modrinth"                    : project.modrinth,
        "discord"                     : project.discord,
        "license"                     : project.license,
        "icon"                        : project.icon,
        "minecraft_range"             : project.minecraft_range,
        "loader_version"              : project.loader_version,
        "min_loader_version"          : project.min_loader_version,
        "min_java"                    : project.min_java,
        "neoforge_minecraft_range"                    : project.neoforge_minecraft_range
]

processResources {
    inputs.properties(modProps)

    filesMatching(["fabric.mod.json", "quilt.mod.json", "META-INF/neoforge.mods.toml", "eslium.mixins.json"]) {
        expand(modProps)
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

tasks.jar {
    archiveFileName = "${rootProject.name}-${version}+${minecraft_version}.jar"
    exclude("net/neoforged/**")
}

java {
	//withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

loom {
    accessWidenerPath = file("src/main/resources/eslium.accesswidener")

        runs {
        client {
            programArgs "--username", "Username"
        }
    }
}
