plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.version
group = project.group

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

def modProps = [
        "group"                 : project.group,
        "id"                      : project.id,
        "name"                    : project.name,
        "version"                 : project.version,
        "description"                 : project.description,
        "author"                     : project.author,
        "homepage"                    : project.homepage,
        "sources"                    : project.sources,
        "issues"                    : project.issues,
        "discord"                     : project.discord,
        "license"                     : project.license,
        "icon"                        : project.icon,
        "constraint_minecraft"             : project.constraint_minecraft,
        "loader_version"              : project.loader_version,
        "constraint_fabric_loader"          : project.constraint_fabric_loader,
        "constraint_java"                    : project.constraint_java,
        "maven_minecraft"                    : project.maven_minecraft,
        "java_target"                    : project.java_target
]

processResources {
    inputs.properties(modProps)

    filesMatching(["fabric.mod.json", "quilt.mod.json", "META-INF/neoforge.mods.toml", "META-INF/mods.toml", "eslium.mixins.json"]) {
        expand(modProps)
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_target.toInteger()
}

tasks.jar {
    archiveFileName = "${rootProject.name}-${version}+${minecraft_version}.jar"
    exclude("net/neoforged/**")
    exclude("net/minecraftforge/**")
}

java {
	//withSourcesJar()

	sourceCompatibility = JavaVersion.toVersion(java_target)
	targetCompatibility = JavaVersion.toVersion(java_target)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

loom {
    accessWidenerPath = file("src/main/resources/eslium.accesswidener")

        runs {
        client {
            programArgs "--username", "Username"
        }
    }
}