# Gradle Properties
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=true

# Common Properties
maven_group=net.solmey.eslium
archives_base_name=eslium
minecraft_version=26.3-pre-1


# Fabric Properties - https://fabricmc.net/develop
loader_version=0.19.5
loom_version=1.17-SNAPSHOT


# Mod Properties
mod_id=eslium
mod_name=Eslium
mod_version=4.6.0
# See https://semver.org/
description=Predicts server actions to reduce latency effects
authors=Solmey
homepage=https://modrinth.com/project/zaVwh7an
modrinth=https://modrinth.com/project/zaVwh7an
discord=https://discord.gg/FVq3j5heAc
license=CC-BY-NC 4.0
icon=assets/eslium/icon.png

#Dependencies
min_java=25

min_loader_version=0.16.0
minecraft_range=26.3-pre.1
# https://wiki.fabricmc.net/documentation:fabric_mod_json
