# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Common Properties
group=net.solmey.eslium
minecraft_version=26.3

# Fabric Properties
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
id=eslium
name=Eslium
version=4.6.0
# https://semver.org/
description=Simulates zero latency by predicting server actions
authors=Solmey
homepage=https://modrinth.com/project/zaVwh7an
sources=https://github.com/Solmeye/Eslium
issues=https://github.com/Solmeye/Eslium/issues
discord=https://discord.gg/FVq3j5heAc
license=CC-BY-NC-4.0
icon=assets/eslium/icon.png

#Dependencies
min_java=25
min_loader_version=0.16.0
minecraft_range==26.3